<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Contact' => '',
    'Home' => '',
    'Logout' => '',
    'My Company' => '',
    'Sign In' => '',
    'Sign Up' => '',
    'Status' => '',
    'Are you sure you want to delete this item?' => 'Sei sicuro di voler eliminare questo articolo?',
    'Congratulations!' => 'Congratulazioni!',
    'Create' => 'creare',
    'Create {modelClass}' => 'creare {modelClass}',
    'Created At' => 'creato il',
    'Delete' => 'cancellare',
    'Get started with Yii' => 'Inizia con Yii',
    'Heading' => 'titolo',
    'ID' => 'ID',
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.' => 'Lorem ipsum dolor sit amet , consectetur adipisicing elit , sed do eiusmod Tempor ut incididunt labore et dolore magna aliqua . Ut enim ad minim veniam , quis nostrud esercitazioni ullamco laboris nisi ut aliquip ex ea Commodo consequat . Duis Aute Irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur .',
    'Message' => 'messaggio',
    'My Yii Application' => 'My Yii Application',
    'Permissions' => 'Autorizzazioni',
    'Reset' => 'reset',
    'Search' => 'ricerca',
    'Statuses' => 'Statuses',
    'Update' => 'aggiornare',
    'Update {modelClass}: ' => 'aggiornare {modelClass} :',
    'Updated At' => 'aggiornato A',
    'Yii Documentation' => 'Yii Documentazione',
    'Yii Extensions' => 'Yii Extensions',
    'Yii Forum' => 'Forum Yii',
    'You have successfully created your Yii-powered application.' => 'È stato creato l\'applicazione Yii - powered .',
];
