<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Contact' => '',
    'Home' => '',
    'Logout' => '',
    'My Company' => '',
    'Sign In' => '',
    'Sign Up' => '',
    'Status' => '',
    'Are you sure you want to delete this item?' => 'あなたはこの項目を削除してもよろしいていますか？',
    'Congratulations!' => 'おめでとう！',
    'Create' => '作る',
    'Create {modelClass}' => '作る {modelClass}',
    'Created At' => 'で作成された',
    'Delete' => '削除',
    'Get started with Yii' => 'Yiiの入門',
    'Heading' => 'ヘディング',
    'ID' => 'ID',
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.' => 'Loremのイプサムの嘆きは、 AMET座るconsectetur adipisicing ELIT 、 eiusmod incididunt UTをtemporんsedのlaboreらdoloreマグナaliqua 。 UT enim広告ミニムveniam 、 QUISのnostrud exercitationのullamco laborisのNiSiのUTのaliquipのexのEA commodoのconsequat 。 Duisのauteのirure嘆きでreprehenderitでvoluptate velit ESSE cillum dolore EU fugiatのnullaのpariatur 。',
    'Message' => 'メッセージ',
    'My Yii Application' => 'マイYiiのアプリケーション',
    'Permissions' => 'パーミッション',
    'Reset' => 'リセット',
    'Search' => '検索',
    'Statuses' => 'ステータス',
    'Update' => 'アップデート',
    'Update {modelClass}: ' => 'アップデート {modelClass} ：',
    'Updated At' => 'で更新',
    'Yii Documentation' => 'Yiiのドキュメント',
    'Yii Extensions' => 'Yiiのエクステンション',
    'Yii Forum' => 'Yiiのフォーラム',
    'You have successfully created your Yii-powered application.' => 'あなたが正常にYiiのパワードアプリケーションを作成した。',
];
