<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Contact' => '',
    'Home' => '',
    'Logout' => '',
    'My Company' => '',
    'Sign In' => '',
    'Sign Up' => '',
    'Status' => '',
    'Are you sure you want to delete this item?' => 'Sind Sie sicher, Sie wollen diesen Inhalt löschen ?',
    'Congratulations!' => 'Herzlichen Glückwunsch!',
    'Create' => 'schaffen',
    'Create {modelClass}' => 'schaffen {modelClass}',
    'Created At' => 'Erstellt am',
    'Delete' => 'löschen',
    'Get started with Yii' => 'Machen Sie sich mit Yii begonnen',
    'Heading' => 'Überschrift',
    'ID' => 'Identifikation',
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit , sed nicht eiusmod TEMPOR incididunt ut labore et dolore magna aliqua . Ut enim ad minim veniam , quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat . Duis aute Irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur .',
    'Message' => 'Nachricht',
    'My Yii Application' => 'Meine Yii-Anwendung',
    'Permissions' => 'Berechtigungen',
    'Reset' => 'rücksetzen',
    'Search' => 'Suche',
    'Statuses' => 'Status',
    'Update' => 'Aktualisierung',
    'Update {modelClass}: ' => 'Aktualisierung {modelClass}:',
    'Updated At' => 'aktualisiert An',
    'Yii Documentation' => 'Yii Dokumentation',
    'Yii Extensions' => 'Yü -Erweiterungen',
    'Yii Forum' => 'Yii Forum',
    'You have successfully created your Yii-powered application.' => 'Sie haben Ihre Yü -powered Anwendung erstellt.',
];
